name: cs612
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona
  - geopandas
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - python
  - pytorch
  - rasterio
  - rasterstats
  - torchvision
  - whitebox