name: cs612
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - matplotlib
  - numpy
  - python
  - rasterio
  - ipykernel
  - jupyterlab
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - whitebox
  - seaborn
  - ipywidgets
  - tqdm