name: earthscape
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - blas=*=openblas
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm
  - numpy
  - pandas
  - geopandas
  - rasterio
  - fiona
  - whitebox
  - matplotlib
  - seaborn