name: earthscape
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - geopandas
  - rasterio
  - whitebox
  - seaborn
  - fiona
  - matplotlib
  - ipywidgets
  - tqdm
  - ipykernel
  - jupyterlab
  - pip:
    - torch
    - torchvision
    - torchinfo
    - hyppo
    - segmentation-models-pytorch