name: earthscape
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - geopandas
  - rasterio
  - whitebox
  - seaborn
  - fiona
  - matplotlib
  - ipywidgets
  - tqdm
  - ipykernel
  - jupyterlab
  - torchinfo
  - pip:
    - torch
    - torchvision
    - -e .