
experiment:
  root: experiments/classification/tests2
  seed: 111


data:
  root: data
  dirs: 
    # - warren/patches
    # - howevalley/patches
    # - sonora/patches
    - smoke/patches
  input:
    dem:
      channels:
        - dem.tif
    # aerial:
    #   channels:
    #     - aerialr.tif
    #     - aerialg.tif
    #     - aerialb.tif


splits:
  root: splits/esv1p1_splits
  glob:
    train: "*train_id.geojson"
    val: "*val_id.geojson"
    test: "*test_id.geojson"
    cross: "*test_cd.geojson"


norm:
  root: splits/esv1p1_splits
  glob: "*train_stats.csv"
  normalize: true


dataloader:
  base:
    batch_size: 4
    num_workers: 0
    persistent_workers: false
    prefetch_factor: null
  train:
    augment: true
    shuffle: true
    drop_last: true
  eval:
    augment: false
    shuffle: false
    drop_last: false


model: 
  encoder: resnet18
  image_size: 256
  output_size: 7
  compile: false


labels:
  root: data
  glob: "*areas.csv"
  area_threshold: 0.0        # supervision labels - None: use area-proportions (need softmax), float: create one-hots of class presence by area proportion


training:
  num_epochs: 5    


optimizer:
  name: adam
  params:
    lr: 0.001
    weight_decay: 0.0
    betas: 
      - 0.9
      - 0.999


loss:
  name: bcefocal
  params:
    pos_weight: null
    gamma: 0
    alpha: null
    reduction: 'mean'
  

early_stop:
  patience: 5
  min_delta: 0.0
  warmup_epochs: 5


eval:
  optimize_clf_thresholds: true